import { Badge, BadgeSeries, Rarity } from './types';

export const BADGES: Badge[] = [
  // ── Animals Series ──────────────────────────────────────────────
  {
    id: 'badge_panda',
    name: '熊猫先生',
    description: '憨态可掬的国宝徽章',
    rarity: 'common',
    series: 'animals',
    emoji: '🐼',
    color: '#1a1a2e',
    bgGradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    dropRate: 0.08,
    storyText: '来自四川竹林深处的神秘使者，带着竹叶清香降临你的冰箱门。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
  },
  {
    id: 'badge_cat',
    name: '宇宙猫咪',
    description: '漂浮在星际间的神秘猫',
    rarity: 'rare',
    series: 'animals',
    emoji: '🐱',
    color: '#ff6b6b',
    bgGradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    dropRate: 0.05,
    storyText: '当猫咪凝视深渊时，深渊也在好奇地看着猫咪。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
  },
  {
    id: 'badge_fox',
    name: '狡黠狐狸',
    description: '九尾之力的封印徽章',
    rarity: 'epic',
    series: 'animals',
    emoji: '🦊',
    color: '#ff9500',
    bgGradient: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    dropRate: 0.025,
    storyText: '传说中每收集一枚，便能获得一分狡智。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'star',
  },
  {
    id: 'badge_dragon',
    name: '神龙降世',
    description: '东方神龙的传承印记',
    rarity: 'legendary',
    series: 'animals',
    emoji: '🐉',
    color: '#ffd700',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    dropRate: 0.008,
    storyText: '上古神龙在人间留下的印记，持有者将获得无尽的好运。',
    obtainMethod: '扭蛋保底 / 集齐动物系列',
    modelType: 'diamond',
  },
  {
    id: 'badge_penguin',
    name: '南极企鹅',
    description: '来自冰川的冷静使者',
    rarity: 'common',
    series: 'animals',
    emoji: '🐧',
    color: '#2d3436',
    bgGradient: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
    dropRate: 0.08,
    storyText: '企鹅说：我就是为冰箱门而生的！',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
  },
  {
    id: 'badge_owl',
    name: '智慧猫头鹰',
    description: '深夜守护者的徽章',
    rarity: 'rare',
    series: 'animals',
    emoji: '🦉',
    color: '#6c5ce7',
    bgGradient: 'linear-gradient(135deg, #a29bfe 0%, #6c5ce7 100%)',
    dropRate: 0.05,
    storyText: '凌晨三点，它依然睁着明亮的眼睛凝视着你的冰箱。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
  },

  // ── Food Series ──────────────────────────────────────────────────
  {
    id: 'badge_pizza',
    name: '至尊比萨',
    description: '午夜食欲的具现化',
    rarity: 'common',
    series: 'food',
    emoji: '🍕',
    color: '#e17055',
    bgGradient: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
    dropRate: 0.08,
    storyText: '每一片都承载着对完美生活的渴望。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
  },
  {
    id: 'badge_ramen',
    name: '深夜拉面',
    description: '魂穿日本的灵魂食物',
    rarity: 'rare',
    series: 'food',
    emoji: '🍜',
    color: '#fdcb6e',
    bgGradient: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
    dropRate: 0.05,
    storyText: '一碗好面，抵过万语言。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
  },
  {
    id: 'badge_sushi',
    name: '传说寿司',
    description: '东瀛匠人毕生之作',
    rarity: 'epic',
    series: 'food',
    emoji: '🍣',
    color: '#00b894',
    bgGradient: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    dropRate: 0.025,
    storyText: '海的味道，凝固在这一枚小小的徽章之中。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
  },
  {
    id: 'badge_birthday_cake',
    name: '无限蛋糕',
    description: '永远过生日的神奇甜点',
    rarity: 'legendary',
    series: 'food',
    emoji: '🎂',
    color: '#fd79a8',
    bgGradient: 'linear-gradient(135deg, #f8cdda 0%, #1d2671 100%)',
    dropRate: 0.008,
    storyText: '每次看到它，都感觉今天是自己的生日。',
    obtainMethod: '生日活动 / 扭蛋保底',
    modelType: 'star',
  },
  {
    id: 'badge_taco',
    name: '玉米卷',
    description: '墨西哥风味的快乐徽章',
    rarity: 'common',
    series: 'food',
    emoji: '🌮',
    color: '#fdcb6e',
    bgGradient: 'linear-gradient(135deg, #ffeaa7 0%, #dfe6e9 100%)',
    dropRate: 0.08,
    storyText: '人生就像玉米卷，要用双手捧住幸福。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
  },

  // ── Space Series ─────────────────────────────────────────────────
  {
    id: 'badge_rocket',
    name: '星际火箭',
    description: '驶向未知宇宙的勇气',
    rarity: 'rare',
    series: 'space',
    emoji: '🚀',
    color: '#74b9ff',
    bgGradient: 'linear-gradient(135deg, #0c3483 0%, #a2b6df 100%)',
    dropRate: 0.05,
    storyText: '3, 2, 1... 点火！向着星辰出发！',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
  },
  {
    id: 'badge_planet',
    name: '孤独行星',
    description: '流浪在宇宙边缘的星球',
    rarity: 'common',
    series: 'space',
    emoji: '🪐',
    color: '#a29bfe',
    bgGradient: 'linear-gradient(135deg, #6a3093 0%, #a044ff 100%)',
    dropRate: 0.08,
    storyText: '即使孤独，也要发出自己的光芒。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
  },
  {
    id: 'badge_blackhole',
    name: '黑洞使者',
    description: '宇宙终极力量的象征',
    rarity: 'legendary',
    series: 'space',
    emoji: '🌀',
    color: '#2d3436',
    bgGradient: 'linear-gradient(135deg, #000000 0%, #434343 100%)',
    dropRate: 0.008,
    storyText: '连光都无法逃脱的引力，但徽章收藏家却做到了。',
    obtainMethod: '扭蛋保底 / 集齐宇宙系列',
    modelType: 'diamond',
  },
  {
    id: 'badge_alien',
    name: '外星访客',
    description: '来自第三类接触的礼物',
    rarity: 'epic',
    series: 'space',
    emoji: '👽',
    color: '#55efc4',
    bgGradient: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    dropRate: 0.025,
    storyText: '他们终于来了，但只是为了说一声"嗨"。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
  },
  {
    id: 'badge_comet',
    name: '幸运彗星',
    description: '千年一遇的幸运使者',
    rarity: 'rare',
    series: 'space',
    emoji: '☄️',
    color: '#fdcb6e',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    dropRate: 0.05,
    storyText: '它划过天际时，记得许下心愿。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'star',
  },

  // ── Nature Series ────────────────────────────────────────────────
  {
    id: 'badge_cherry_blossom',
    name: '樱花飞雪',
    description: '转瞬即逝的绝美瞬间',
    rarity: 'epic',
    series: 'nature',
    emoji: '🌸',
    color: '#fd79a8',
    bgGradient: 'linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)',
    dropRate: 0.025,
    storyText: '花开堪折直须折，莫待无花空折枝。',
    obtainMethod: '春季限定 / 扭蛋抽奖',
    modelType: 'star',
  },
  {
    id: 'badge_rainbow',
    name: '彩虹约定',
    description: '风雨之后的美丽承诺',
    rarity: 'common',
    series: 'nature',
    emoji: '🌈',
    color: '#a29bfe',
    bgGradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 30%, #4facfe 60%, #00f2fe 100%)',
    dropRate: 0.08,
    storyText: '每场风雨之后，总会有属于你的彩虹。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
  },
  {
    id: 'badge_aurora',
    name: '极光奇境',
    description: '北极天空的神秘画卷',
    rarity: 'legendary',
    series: 'nature',
    emoji: '🌌',
    color: '#00b894',
    bgGradient: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    dropRate: 0.008,
    storyText: '北极的夜空，为你永久定格。',
    obtainMethod: '冬季活动 / 扭蛋保底',
    modelType: 'diamond',
  },
  {
    id: 'badge_leaf',
    name: '秋日落叶',
    description: '最后一片叶子的坚守',
    rarity: 'common',
    series: 'nature',
    emoji: '🍂',
    color: '#e17055',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    dropRate: 0.08,
    storyText: '每一片落叶都是大树对土地的感恩。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
  },
  {
    id: 'badge_mushroom',
    name: '神奇蘑菇',
    description: '森林精灵的秘密礼物',
    rarity: 'rare',
    series: 'nature',
    emoji: '🍄',
    color: '#e17055',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #ee0979 100%)',
    dropRate: 0.05,
    storyText: '在魔法森林中，只有真正的探险者才能找到它。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
  },

  // ── Tech Series ──────────────────────────────────────────────────
  {
    id: 'badge_robot',
    name: '友好机器人',
    description: '未来科技的温情使者',
    rarity: 'common',
    series: 'tech',
    emoji: '🤖',
    color: '#74b9ff',
    bgGradient: 'linear-gradient(135deg, #89f7fe 0%, #66a6ff 100%)',
    dropRate: 0.08,
    storyText: 'BEEP BOOP - 已成功接入感情模块。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
  },
  {
    id: 'badge_computer',
    name: '像素方块',
    description: '游戏世界的基础单元',
    rarity: 'rare',
    series: 'tech',
    emoji: '💻',
    color: '#636e72',
    bgGradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    dropRate: 0.05,
    storyText: '一千行代码，不如一枚好徽章。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
  },
  {
    id: 'badge_ai',
    name: '奇点降临',
    description: '人工智能觉醒的历史瞬间',
    rarity: 'legendary',
    series: 'tech',
    emoji: '🧠',
    color: '#6c5ce7',
    bgGradient: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    dropRate: 0.008,
    storyText: '它开始思考，因此它存在。',
    obtainMethod: '科技系列集齐 / 扭蛋保底',
    modelType: 'diamond',
  },
  {
    id: 'badge_gamepad',
    name: '游戏手柄',
    description: '无数个童年夜晚的见证者',
    rarity: 'epic',
    series: 'tech',
    emoji: '🎮',
    color: '#6c5ce7',
    bgGradient: 'linear-gradient(135deg, #8e2de2 0%, #4a00e0 100%)',
    dropRate: 0.025,
    storyText: 'PLAYER 1, INSERT COIN... 但你不需要硬币。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
  },

  // ── Fantasy Series ───────────────────────────────────────────────
  {
    id: 'badge_wizard',
    name: '古老法师',
    description: '掌握时间魔法的智者',
    rarity: 'epic',
    series: 'fantasy',
    emoji: '🧙',
    color: '#6c5ce7',
    bgGradient: 'linear-gradient(135deg, #2980b9 0%, #6dd5fa 100%)',
    dropRate: 0.025,
    storyText: '所有的魔法都源于对世界深深的热爱。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'star',
  },
  {
    id: 'badge_unicorn',
    name: '独角仙兽',
    description: '纯洁与奇迹的象征',
    rarity: 'legendary',
    series: 'fantasy',
    emoji: '🦄',
    color: '#fd79a8',
    bgGradient: 'linear-gradient(135deg, #f8cdda 0%, #1d2671 100%)',
    dropRate: 0.008,
    storyText: '传说只有拥有纯粹心灵的人，才能看见独角兽的踪迹。',
    obtainMethod: '幻想系列集齐 / 扭蛋保底',
    modelType: 'diamond',
  },
  {
    id: 'badge_fairy',
    name: '精灵仙子',
    description: '森林间跳舞的精灵',
    rarity: 'rare',
    series: 'fantasy',
    emoji: '🧚',
    color: '#00b894',
    bgGradient: 'linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%)',
    dropRate: 0.05,
    storyText: '每一次愿望实现，都有精灵仙子在背后默默守护。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'star',
  },
  {
    id: 'badge_crystal',
    name: '魔法水晶',
    description: '储存着古老咒语的宝石',
    rarity: 'common',
    series: 'fantasy',
    emoji: '💎',
    color: '#74b9ff',
    bgGradient: 'linear-gradient(135deg, #89f7fe 0%, #66a6ff 100%)',
    dropRate: 0.08,
    storyText: '每块水晶都封印着一段被遗忘的故事。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'diamond',
  },

  // ── Sports Series ────────────────────────────────────────────────
  {
    id: 'badge_trophy',
    name: '冠军奖杯',
    description: '永恒胜利的象征',
    rarity: 'epic',
    series: 'sports',
    emoji: '🏆',
    color: '#ffd700',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    dropRate: 0.025,
    storyText: '每一个冠军背后，都有无数次默默无闻的练习。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
  },
  {
    id: 'badge_medal',
    name: '黄金勋章',
    description: '奥运精神的具现',
    rarity: 'common',
    series: 'sports',
    emoji: '🥇',
    color: '#ffd700',
    bgGradient: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
    dropRate: 0.08,
    storyText: '更快、更高、更强——永不放弃。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
  },

  // ── Music Series ─────────────────────────────────────────────────
  {
    id: 'badge_guitar',
    name: '摇滚魂',
    description: '音乐灵魂的外在表达',
    rarity: 'rare',
    series: 'music',
    emoji: '🎸',
    color: '#e17055',
    bgGradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    dropRate: 0.05,
    storyText: '每一次拨弦，都是对生命的一次呐喊。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
  },
  {
    id: 'badge_notes',
    name: '天籁音符',
    description: '凝固的旋律，永恒的感动',
    rarity: 'common',
    series: 'music',
    emoji: '🎵',
    color: '#6c5ce7',
    bgGradient: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
    dropRate: 0.08,
    storyText: '有些话用语言说不出口，但音乐能。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
  },
  {
    id: 'badge_vinyl',
    name: '黑胶传奇',
    description: '模拟音乐时代的最后见证',
    rarity: 'legendary',
    series: 'music',
    emoji: '💿',
    color: '#2d3436',
    bgGradient: 'linear-gradient(135deg, #434343 0%, #000000 100%)',
    dropRate: 0.008,
    storyText: '在数字洪流中，它坚守着音乐本来的温度。',
    obtainMethod: '音乐系列集齐 / 扭蛋保底',
    modelType: 'diamond',
  },
  {
    id: 'badge_piano',
    name: '月光琴键',
    description: '贝多芬遗留在月光下的印记',
    rarity: 'epic',
    series: 'music',
    emoji: '🎹',
    color: '#2d3436',
    bgGradient: 'linear-gradient(135deg, #373b44 0%, #4286f4 100%)',
    dropRate: 0.025,
    storyText: '月光奏鸣曲的第一个音符，在这里永恒回响。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
  },
];

export const BADGE_MAP: Record<string, Badge> = Object.fromEntries(
  BADGES.map((b) => [b.id, b])
);

export const SERIES_LIST: BadgeSeries[] = [
  'animals',
  'food',
  'space',
  'nature',
  'tech',
  'fantasy',
  'sports',
  'music',
];

export const SERIES_NAMES: Record<BadgeSeries, string> = {
  animals: '动物王国',
  food: '美食天堂',
  space: '宇宙探索',
  nature: '自然奇观',
  tech: '科技未来',
  fantasy: '奇幻仙境',
  sports: '竞技精神',
  music: '音乐灵魂',
};

export const SERIES_EMOJIS: Record<BadgeSeries, string> = {
  animals: '🦁',
  food: '🍔',
  space: '🚀',
  nature: '🌿',
  tech: '⚡',
  fantasy: '✨',
  sports: '🏅',
  music: '🎶',
};

export const RARITY_NAMES: Record<string, string> = {
  common: '普通',
  rare: '稀有',
  epic: '史诗',
  legendary: '传说',
};

export const RARITY_COLORS: Record<string, string> = {
  common: '#9ca3af',
  rare: '#3b82f6',
  epic: '#8b5cf6',
  legendary: '#f59e0b',
};

export const RARITY_GLOW: Record<string, string> = {
  common: 'rgba(156,163,175,0.4)',
  rare: 'rgba(59,130,246,0.6)',
  epic: 'rgba(139,92,246,0.6)',
  legendary: 'rgba(245,158,11,0.8)',
};

export const BADGES_BY_SERIES = (series: BadgeSeries) =>
  BADGES.filter((b) => b.series === series);

export const BADGES_BY_RARITY = (rarity: Rarity) =>
  BADGES.filter((b) => b.rarity === rarity);
