import { Badge, BadgeSeries, Rarity } from './types';

export const BADGES: Badge[] = [
  // ── Toy Story ─────────────────────────────────────────────────────
  {
    id: 'badge_woody',
    name: '胡迪',
    description: '安迪最爱的牛仔警长玩具',
    rarity: 'epic',
    series: 'toy_story',
    emoji: '🤠',
    color: '#c8860a',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #c8860a 55%, #8B4513 100%)',
    dropRate: 0.025,
    storyText: '你是我见过最好的牛仔，永远！',
    obtainMethod: '扭蛋抽奖',
    modelType: 'star',
    modelUrl: '/models/badge_woody.glb',
  },
  {
    id: 'badge_buzz',
    name: '巴斯光年',
    description: '来自银河护卫队的宇宙飞侠',
    rarity: 'legendary',
    series: 'toy_story',
    emoji: '🚀',
    color: '#5c6bc0',
    bgGradient: 'linear-gradient(135deg, #1a1a3e 0%, #2d3561 40%, #5c6bc0 75%, #c5cae9 100%)',
    dropRate: 0.008,
    storyText: '飞向无限，直达宇宙的那一端！',
    obtainMethod: '扭蛋保底 / 集齐玩具总动员系列',
    modelType: 'diamond',
    modelUrl: '/models/badge_buzz.glb',
  },
  {
    id: 'badge_alien',
    name: '三眼仔',
    description: '披萨星球的神圣守护者',
    rarity: 'common',
    series: 'toy_story',
    emoji: '👽',
    color: '#55efc4',
    bgGradient: 'linear-gradient(135deg, #1a472a 0%, #2ecc71 50%, #a29bfe 100%)',
    dropRate: 0.08,
    storyText: '爪子！披萨星球的神圣守护之物已降临你的冰箱。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_alien.glb',
  },
  {
    id: 'badge_forky',
    name: '叉叉',
    description: '宝尼亲手制作的艺术品玩具',
    rarity: 'common',
    series: 'toy_story',
    emoji: '🍴',
    color: '#74b9ff',
    bgGradient: 'linear-gradient(135deg, #f5f5f5 0%, #b2bec3 50%, #74b9ff 100%)',
    dropRate: 0.08,
    storyText: '我是垃圾！……不，你是宝尼最珍贵的宝贝。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_forky.glb',
  },
  {
    id: 'badge_bo_peep',
    name: '牧羊女宝贝',
    description: '独立勇敢的瓷偶牧羊女',
    rarity: 'rare',
    series: 'toy_story',
    emoji: '🐑',
    color: '#fd79a8',
    bgGradient: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 40%, #fbc2eb 100%)',
    dropRate: 0.05,
    storyText: '独立、勇敢，她从不等待别人来拯救。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
    modelUrl: '/models/badge_bo_peep.glb',
  },
  {
    id: 'badge_buzz_helmet',
    name: '巴斯头盔与翅膀',
    description: '宇宙飞侠的标志性战甲符号',
    rarity: 'rare',
    series: 'toy_story',
    emoji: '🛡️',
    color: '#a29bfe',
    bgGradient: 'linear-gradient(135deg, #4a00e0 0%, #8e2de2 50%, #c3cfe2 100%)',
    dropRate: 0.05,
    storyText: '紫色合金头盔与白色翅膀，承载着宇宙飞侠的无限荣耀。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
    modelUrl: '/models/badge_buzz_helmet.glb',
  },
  {
    id: 'badge_andy_footprint',
    name: '安迪的脚印',
    description: '鞋底永久的爱的印记',
    rarity: 'common',
    series: 'toy_story',
    emoji: '👟',
    color: '#e17055',
    bgGradient: 'linear-gradient(135deg, #ff416c 0%, #ff4b2b 50%, #fdcb6e 100%)',
    dropRate: 0.08,
    storyText: '鞋底的"ANDY"，是爱最深刻也最温柔的印记。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_andy_footprint.glb',
  },
  {
    id: 'badge_rocket_ship',
    name: '太空火箭飞船',
    description: '玩具们梦想中的宇宙座驾',
    rarity: 'epic',
    series: 'toy_story',
    emoji: '🛸',
    color: '#74b9ff',
    bgGradient: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    dropRate: 0.025,
    storyText: '那艘薛定谔的飞船，总在最需要的时候出现。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
    modelUrl: '/models/badge_rocket_ship.glb',
  },

  // ── Monsters Inc / Monsters University ────────────────────────────
  {
    id: 'badge_sulley',
    name: '毛怪',
    description: '怪兽城最顶级的惊吓冠军',
    rarity: 'legendary',
    series: 'monsters_inc',
    emoji: '🐾',
    color: '#2980b9',
    bgGradient: 'linear-gradient(135deg, #1a5276 0%, #2980b9 40%, #7fb3d3 75%, #48c9b0 100%)',
    dropRate: 0.008,
    storyText: '怪兽城惊吓冠军，却因一个叫阿布的小女孩彻底改变了。',
    obtainMethod: '扭蛋保底 / 集齐怪兽电力公司系列',
    modelType: 'diamond',
    modelUrl: '/models/badge_sulley.glb',
  },
  {
    id: 'badge_mike',
    name: '麦克·华斯基',
    description: '怪兽大学惊吓学院明星',
    rarity: 'epic',
    series: 'monsters_inc',
    emoji: '🟢',
    color: '#00b894',
    bgGradient: 'linear-gradient(135deg, #11998e 0%, #38ef7d 55%, #b2f492 100%)',
    dropRate: 0.025,
    storyText: '努力是唯一出路，他用行动证明了这一点！',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
    modelUrl: '/models/badge_mike.glb',
  },
  {
    id: 'badge_boo',
    name: '阿布',
    description: '闯入怪兽城的勇敢小女孩',
    rarity: 'rare',
    series: 'monsters_inc',
    emoji: '🩷',
    color: '#fd79a8',
    bgGradient: 'linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 50%, #d4a4f5 100%)',
    dropRate: 0.05,
    storyText: '哈！她的笑声，点亮了整个怪兽城。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'star',
    modelUrl: '/models/badge_boo.glb',
  },
  {
    id: 'badge_scare_door',
    name: '惊吓电力公司门',
    description: '连接怪兽城与人类世界的传送门',
    rarity: 'rare',
    series: 'monsters_inc',
    emoji: '🚪',
    color: '#6c5ce7',
    bgGradient: 'linear-gradient(135deg, #2d3561 0%, #6c5ce7 50%, #a29bfe 100%)',
    dropRate: 0.05,
    storyText: '每一扇门背后，都藏着一个孩子的梦境与秘密。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
    modelUrl: '/models/badge_scare_door.glb',
  },
  {
    id: 'badge_one_eye_symbol',
    name: '大眼仔单眼符号',
    description: '麦克标志性的独眼图腾',
    rarity: 'common',
    series: 'monsters_inc',
    emoji: '👁️',
    color: '#fdcb6e',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #fdcb6e 55%, #fffde7 100%)',
    dropRate: 0.08,
    storyText: '一只眼睛，看遍怪兽世界的喜怒哀乐。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_one_eye_symbol.glb',
  },
  {
    id: 'badge_mu_emblem',
    name: '怪兽大学校徽',
    description: '惊吓梦想的摇篮',
    rarity: 'common',
    series: 'monsters_inc',
    emoji: '🎓',
    color: '#00b894',
    bgGradient: 'linear-gradient(135deg, #1a3a5c 0%, #2471a3 50%, #f4d03f 100%)',
    dropRate: 0.08,
    storyText: 'MU！这里是每一头怪兽开启惊吓之梦的地方。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
    modelUrl: '/models/badge_mu_emblem.glb',
  },
  {
    id: 'badge_scream_canister',
    name: '惊吓能量瓶',
    description: '储存尖叫能量的蓝色电力罐',
    rarity: 'epic',
    series: 'monsters_inc',
    emoji: '⚡',
    color: '#0984e3',
    bgGradient: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
    dropRate: 0.025,
    storyText: '一声尖叫，足以点亮怪兽城的万家灯火。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'diamond',
    modelUrl: '/models/badge_scream_canister.glb',
  },
  {
    id: 'badge_sulley_tail',
    name: '毛怪大尾巴剪影',
    description: '毛怪那条招牌蓝色大尾巴',
    rarity: 'common',
    series: 'monsters_inc',
    emoji: '🦎',
    color: '#48c9b0',
    bgGradient: 'linear-gradient(135deg, #11998e 0%, #38ef7d 40%, #74b9ff 100%)',
    dropRate: 0.08,
    storyText: '那条独一无二的蓝色大尾巴，是毛怪最有力的表情武器。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_sulley_tail.glb',
  },

  // ── Finding Nemo / Finding Dory ───────────────────────────────────
  {
    id: 'badge_nemo',
    name: '尼莫',
    description: '勇敢的小丑鱼，爸爸的全部',
    rarity: 'common',
    series: 'finding_nemo',
    emoji: '🐠',
    color: '#e17055',
    bgGradient: 'linear-gradient(135deg, #ff9966 0%, #ff5e62 50%, #f5f5f5 100%)',
    dropRate: 0.08,
    storyText: '就算大海那么大，爸爸也一定会找到你。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_nemo.glb',
  },
  {
    id: 'badge_marlin',
    name: '马林',
    description: '横越太平洋寻子的勇敢父亲',
    rarity: 'rare',
    series: 'finding_nemo',
    emoji: '🐡',
    color: '#fdcb6e',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #ff5e62 50%, #fdcb6e 100%)',
    dropRate: 0.05,
    storyText: '担忧是因为爱，而爱让一切冒险都值得。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
    modelUrl: '/models/badge_marlin.glb',
  },
  {
    id: 'badge_dory',
    name: '多莉',
    description: '乐观健忘的蓝色拟刺尾鲷',
    rarity: 'epic',
    series: 'finding_nemo',
    emoji: '🐟',
    color: '#0984e3',
    bgGradient: 'linear-gradient(135deg, #1e90ff 0%, #74b9ff 40%, #f9d423 75%, #000 100%)',
    dropRate: 0.025,
    storyText: '就算忘了一切，也不会忘记一直向前游！',
    obtainMethod: '扭蛋抽奖',
    modelType: 'star',
    modelUrl: '/models/badge_dory.glb',
  },
  {
    id: 'badge_gill',
    name: '吉哥',
    description: '鱼缸中渴望自由的摩里鱼',
    rarity: 'rare',
    series: 'finding_nemo',
    emoji: '🦈',
    color: '#2d3436',
    bgGradient: 'linear-gradient(135deg, #373b44 0%, #4286f4 50%, #636e72 100%)',
    dropRate: 0.05,
    storyText: '每条鱼都渴望归海，自由才是真正的终点。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
    modelUrl: '/models/badge_gill.glb',
  },
  {
    id: 'badge_crush',
    name: '海龟柯鲁斯',
    description: '随洋流冲浪的酷爸爸海龟',
    rarity: 'common',
    series: 'finding_nemo',
    emoji: '🐢',
    color: '#00b894',
    bgGradient: 'linear-gradient(135deg, #1d4e09 0%, #2ecc71 50%, #a8e6cf 100%)',
    dropRate: 0.08,
    storyText: '随洋流漂流，这才是真正的滑浪精神，好兄弟！',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_crush.glb',
  },
  {
    id: 'badge_whale_speak',
    name: '鲸语符号',
    description: '多莉与座头鲸的神秘交流符号',
    rarity: 'common',
    series: 'finding_nemo',
    emoji: '🐋',
    color: '#74b9ff',
    bgGradient: 'linear-gradient(135deg, #2193b0 0%, #6dd5ed 50%, #c7ecee 100%)',
    dropRate: 0.08,
    storyText: '在深海中，多莉用鲸语倾诉着对尼莫的思念。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
    modelUrl: '/models/badge_whale_speak.glb',
  },
  {
    id: 'badge_coral_reef',
    name: '深海珊瑚徽章',
    description: '海底最绚烂的生命乐园',
    rarity: 'legendary',
    series: 'finding_nemo',
    emoji: '🪸',
    color: '#fd79a8',
    bgGradient: 'linear-gradient(135deg, #000428 0%, #004e92 40%, #ff6b6b 70%, #feca57 100%)',
    dropRate: 0.008,
    storyText: '海底世界最绚烂的彩虹，是属于每条鱼的永恒家园。',
    obtainMethod: '扭蛋保底 / 集齐海底总动员系列',
    modelType: 'diamond',
    modelUrl: '/models/badge_coral_reef.glb',
  },

  // ── The Incredibles ───────────────────────────────────────────────
  {
    id: 'badge_mr_incredible',
    name: '超能先生',
    description: '拥有超强力量的超级英雄之父',
    rarity: 'legendary',
    series: 'incredibles',
    emoji: '💪',
    color: '#e74c3c',
    bgGradient: 'linear-gradient(135deg, #c0392b 0%, #e74c3c 50%, #f39c12 100%)',
    dropRate: 0.008,
    storyText: '不论世界如何变，超能先生永远守护着他的家人。',
    obtainMethod: '扭蛋保底 / 集齐超人总动员系列',
    modelType: 'diamond',
    modelUrl: '/models/badge_mr_incredible.glb',
  },
  {
    id: 'badge_elastigirl',
    name: '弹力女超人',
    description: '身形如橡皮筋的超能妈妈',
    rarity: 'epic',
    series: 'incredibles',
    emoji: '✨',
    color: '#e74c3c',
    bgGradient: 'linear-gradient(135deg, #e74c3c 0%, #c0392b 30%, #f39c12 65%, #e74c3c 100%)',
    dropRate: 0.025,
    storyText: '无论何种形态，她永远是最强的超级英雄。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'star',
    modelUrl: '/models/badge_elastigirl.glb',
  },
  {
    id: 'badge_violet',
    name: '巴小倩',
    description: '能隐身与制造力场的超能少女',
    rarity: 'rare',
    series: 'incredibles',
    emoji: '🫧',
    color: '#8b5cf6',
    bgGradient: 'linear-gradient(135deg, #6a3093 0%, #a044ff 50%, #c3cfe2 100%)',
    dropRate: 0.05,
    storyText: '最初渴望隐形，最终勇敢选择闪耀。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
    modelUrl: '/models/badge_violet.glb',
  },
  {
    id: 'badge_dash',
    name: '巴小飞',
    description: '速度超乎常人的超能小学生',
    rarity: 'common',
    series: 'incredibles',
    emoji: '💨',
    color: '#f1c40f',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 50%, #f5f5f5 100%)',
    dropRate: 0.08,
    storyText: '如果每个人都特别，那就没有人特别——但他才不信！',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_dash.glb',
  },
  {
    id: 'badge_jack_jack',
    name: '巴小杰',
    description: '拥有十七种超能力的神秘婴儿',
    rarity: 'rare',
    series: 'incredibles',
    emoji: '🔥',
    color: '#e17055',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #ee0979 50%, #6c5ce7 100%)',
    dropRate: 0.05,
    storyText: '一个婴儿，十七种超能力，无尽的惊喜。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'star',
    modelUrl: '/models/badge_jack_jack.glb',
  },
  {
    id: 'badge_incredibles_logo',
    name: '超人家族 LOGO',
    description: '超级英雄家族的荣耀徽标',
    rarity: 'epic',
    series: 'incredibles',
    emoji: '🦸',
    color: '#e74c3c',
    bgGradient: 'linear-gradient(135deg, #c0392b 0%, #e74c3c 50%, #fdcb6e 100%)',
    dropRate: 0.025,
    storyText: '没有任何逆境能击倒整个超人家族。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
    modelUrl: '/models/badge_incredibles_logo.glb',
  },
  {
    id: 'badge_frozone_symbol',
    name: '超劲先生符号',
    description: '弗罗斯特标志性的冰冻纹章',
    rarity: 'common',
    series: 'incredibles',
    emoji: '❄️',
    color: '#74b9ff',
    bgGradient: 'linear-gradient(135deg, #89f7fe 0%, #66a6ff 50%, #ffffff 100%)',
    dropRate: 0.08,
    storyText: '老兄，你知道我的超级英雄服在哪吗？',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_frozone_symbol.glb',
  },
  {
    id: 'badge_super_car',
    name: '超能车剪影',
    description: '埃德娜设计的超级英雄专属座驾',
    rarity: 'common',
    series: 'incredibles',
    emoji: '🏎️',
    color: '#2d3436',
    bgGradient: 'linear-gradient(135deg, #2d3436 0%, #636e72 50%, #b2bec3 100%)',
    dropRate: 0.08,
    storyText: '埃德娜·摩德亲手设计的战车，速度与科技的结晶。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
    modelUrl: '/models/badge_super_car.glb',
  },

  // ── Cars ──────────────────────────────────────────────────────────
  {
    id: 'badge_mcqueen',
    name: '闪电麦昆',
    description: '年轻气盛的冠军赛车',
    rarity: 'legendary',
    series: 'cars',
    emoji: '⚡',
    color: '#e74c3c',
    bgGradient: 'linear-gradient(135deg, #c0392b 0%, #e74c3c 50%, #f9ca24 100%)',
    dropRate: 0.008,
    storyText: '速度！我就是速度！——第一次踏上赛道时立下的誓言。',
    obtainMethod: '扭蛋保底 / 集齐赛车总动员系列',
    modelType: 'diamond',
    modelUrl: '/models/badge_mcqueen.glb',
  },
  {
    id: 'badge_mater',
    name: '板牙',
    description: '水箱温泉镇最忠诚的拖车好友',
    rarity: 'common',
    series: 'cars',
    emoji: '🔧',
    color: '#b07c4f',
    bgGradient: 'linear-gradient(135deg, #8B4513 0%, #cd853f 50%, #daa520 100%)',
    dropRate: 0.08,
    storyText: '我倒车比其他人前进都快！世界上最忠诚的好朋友。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_mater.glb',
  },
  {
    id: 'badge_sally',
    name: '莎莉',
    description: '离开快车道安居水箱温泉的保时捷',
    rarity: 'rare',
    series: 'cars',
    emoji: '🩵',
    color: '#74b9ff',
    bgGradient: 'linear-gradient(135deg, #2193b0 0%, #6dd5ed 50%, #a3d8f4 100%)',
    dropRate: 0.05,
    storyText: '离开快车道，才发现水箱温泉才是她真正的家。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
    modelUrl: '/models/badge_sally.glb',
  },
  {
    id: 'badge_doc_hudson',
    name: '蓝天博士',
    description: '三届活塞杯冠军的传奇老车',
    rarity: 'epic',
    series: 'cars',
    emoji: '🏁',
    color: '#2980b9',
    bgGradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 35%, #0f3460 65%, #533483 100%)',
    dropRate: 0.025,
    storyText: '三届活塞杯冠军，在水箱温泉找到了比荣耀更珍贵的东西。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'star',
    modelUrl: '/models/badge_doc_hudson.glb',
  },
  {
    id: 'badge_piston_cup',
    name: '活塞杯奖杯',
    description: '赛车界最高荣誉的金色奖杯',
    rarity: 'epic',
    series: 'cars',
    emoji: '🏆',
    color: '#f39c12',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 50%, #c0392b 100%)',
    dropRate: 0.025,
    storyText: '金色活塞杯，承载着每一辆赛车毕生的梦想与荣耀。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
    modelUrl: '/models/badge_piston_cup.glb',
  },
  {
    id: 'badge_95',
    name: '95 号车号徽章',
    description: '闪电麦昆传奇号码的纪念徽章',
    rarity: 'common',
    series: 'cars',
    emoji: '🏅',
    color: '#e74c3c',
    bgGradient: 'linear-gradient(135deg, #ff416c 0%, #ff4b2b 50%, #fdcb6e 100%)',
    dropRate: 0.08,
    storyText: '宝尼写在车窗上的数字，从此成为了赛车传奇。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_95.glb',
  },
  {
    id: 'badge_radiator_springs',
    name: '水箱温泉镇路标',
    description: '66号公路上那个被遗忘的温暖小镇',
    rarity: 'rare',
    series: 'cars',
    emoji: '🛣️',
    color: '#e67e22',
    bgGradient: 'linear-gradient(135deg, #f7971e 0%, #e67e22 40%, #c0392b 65%, #8B4513 100%)',
    dropRate: 0.05,
    storyText: '66号公路旁被时代遗忘的小镇，却是世界上最温暖的地方。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
    modelUrl: '/models/badge_radiator_springs.glb',
  },

  // ── Ratatouille ───────────────────────────────────────────────────
  {
    id: 'badge_remy',
    name: '小米',
    description: '梦想成为大厨的天才小老鼠',
    rarity: 'legendary',
    series: 'ratatouille',
    emoji: '🐀',
    color: '#9b59b6',
    bgGradient: 'linear-gradient(135deg, #6c3483 0%, #9b59b6 40%, #d7bde2 70%, #f5cba7 100%)',
    dropRate: 0.008,
    storyText: '任何人都能做菜——即使是一只小老鼠。',
    obtainMethod: '扭蛋保底 / 集齐美食总动员系列',
    modelType: 'diamond',
    modelUrl: '/models/badge_remy.glb',
  },
  {
    id: 'badge_linguini',
    name: '小林',
    description: '被小米的烹饪天赋所改变的年轻厨师',
    rarity: 'common',
    series: 'ratatouille',
    emoji: '👨‍🍳',
    color: '#e67e22',
    bgGradient: 'linear-gradient(135deg, #f5f5f5 0%, #e0e0e0 40%, #e67e22 75%, #c0392b 100%)',
    dropRate: 0.08,
    storyText: '他掌握了世界上最神奇的烹饪方式——用头发来驱动梦想。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'circle',
    modelUrl: '/models/badge_linguini.glb',
  },
  {
    id: 'badge_chef_hat',
    name: '料理鼠王厨师帽',
    description: '征服美食王国的高耸白帽',
    rarity: 'rare',
    series: 'ratatouille',
    emoji: '🍳',
    color: '#f5cba7',
    bgGradient: 'linear-gradient(135deg, #ffffff 0%, #f5f5f5 45%, #e0e0e0 100%)',
    dropRate: 0.05,
    storyText: '一顶厨师帽，承载着小老鼠征服美食王国的伟大梦想。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'hexagon',
    modelUrl: '/models/badge_chef_hat.glb',
  },
  {
    id: 'badge_french_dish',
    name: '法式料理盘',
    description: '让最挑剔评论家动容的精致料理',
    rarity: 'epic',
    series: 'ratatouille',
    emoji: '🍽️',
    color: '#f39c12',
    bgGradient: 'linear-gradient(135deg, #f5f5f5 0%, #e8e8e8 30%, #c8b560 60%, #f39c12 100%)',
    dropRate: 0.025,
    storyText: '一道完美的法式料理，足以让最挑剔的美食评论家落泪。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'shield',
    modelUrl: '/models/badge_french_dish.glb',
  },
  {
    id: 'badge_eiffel_tower',
    name: '巴黎铁塔剪影',
    description: '美食与艺术共存的浪漫之城',
    rarity: 'rare',
    series: 'ratatouille',
    emoji: '🗼',
    color: '#2c3e50',
    bgGradient: 'linear-gradient(135deg, #2c3e50 0%, #3d5a80 40%, #4a90d9 70%, #7eb8f7 100%)',
    dropRate: 0.05,
    storyText: '巴黎的夜空下，美食与艺术共同守护着这座铁塔。',
    obtainMethod: '扭蛋抽奖',
    modelType: 'diamond',
    modelUrl: '/models/badge_eiffel_tower.glb',
  },
];

export const BADGE_MAP: Record<string, Badge> = Object.fromEntries(
  BADGES.map((b) => [b.id, b])
);

export const SERIES_LIST: BadgeSeries[] = [
  'toy_story',
  'monsters_inc',
  'finding_nemo',
  'incredibles',
  'cars',
  'ratatouille',
];

export const SERIES_NAMES: Record<BadgeSeries, string> = {
  toy_story: '玩具总动员',
  monsters_inc: '怪兽电力公司',
  finding_nemo: '海底总动员',
  incredibles: '超人总动员',
  cars: '赛车总动员',
  ratatouille: '美食总动员',
};

export const SERIES_EMOJIS: Record<BadgeSeries, string> = {
  toy_story: '🤠',
  monsters_inc: '🐾',
  finding_nemo: '🐠',
  incredibles: '🦸',
  cars: '⚡',
  ratatouille: '🐀',
};

export const RARITY_NAMES: Record<string, string> = {
  common: '普通',
  rare: '稀有',
  epic: '史诗',
  legendary: '传说',
};

export const RARITY_COLORS: Record<string, string> = {
  common: '#9ca3af',
  rare: '#3b82f6',
  epic: '#8b5cf6',
  legendary: '#f59e0b',
};

export const RARITY_GLOW: Record<string, string> = {
  common: 'rgba(156,163,175,0.4)',
  rare: 'rgba(59,130,246,0.6)',
  epic: 'rgba(139,92,246,0.6)',
  legendary: 'rgba(245,158,11,0.8)',
};

export const BADGES_BY_SERIES = (series: BadgeSeries) =>
  BADGES.filter((b) => b.series === series);

export const BADGES_BY_RARITY = (rarity: Rarity) =>
  BADGES.filter((b) => b.rarity === rarity);
